[workspace]
resolver = "2"
members = [
    "cargo-obs-build",
    "libobs",
    "libobs-source-macro",
    "libobs-sources",
    "libobs-window-helper",
    "libobs-wrapper",
    "libobs-encoders/*",

    "examples/*",
]
exclude = ["examples/tauri-app"]

[workspace.metadata]
libobs-version = "31.0.3"
libobs-cache-dir = "../obs-build"
