[workspace]
resolver="2"
members = [
    "cargo-obs-build",
    "libobs",
    "libobs-display-tester",
    "libobs-source-macro",
    "libobs-sources",
    "libobs-window-helper",
    "libobs-wrapper"
]

[workspace.metadata]
libobs-version="31.0.3"
libobs-cache-dir="../obs-build"
