[package]
name = "libobs-source-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
quote = "1.0.36"
syn = "2.0.72"

[lib]
name = "libobs_source_macro"
path = "src/lib.rs"
proc-macro = true
