[package]
name = "libobs-sources"
version = "0.1.0"
edition = "2021"

[dependencies]
libobs = { path = "../libobs", version = "0.1.3" }
num-derive = "0.4.2"
num-traits = "0.2.19"
libobs-source-macro = { path = "../libobs-source-macro", version = "0.1.0" }
anyhow = "1.0.86"

[features]
default = ["window-list"]
window-list = ["dep:libobs-window-helper"]

[target.'cfg(target_family = "windows")'.dependencies]
display-info = "0.5.1"
libobs-window-helper = { version = "0.1.0", optional = true }

[dev-dependencies]
lazy_static = "1.5.0"

[package.metadata]
libobs-version="30.2.2"
libobs-cache-dir="../obs-build"