[package]
name = "libobs-sources"
description = "A helper crate to create sources for OBS"
version = "0.1.1"
repository = "https://github.com/sshcrack/libobs-rs"
readme = "README.md"
authors = ["sshcrack"]
categories = ["multimedia::video", "multimedia::audio", "multimedia", "multimedia::encoding"]
keywords = ["obs", "libobs", "video", "recording", "screen-recording"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
libobs = { package = "libobs-new", version = "2.0.2", path = "../libobs" }
libobs-wrapper = { path = "../libobs-wrapper", version = "0.2.2" }
num-derive = "0.4.2"
num-traits = "0.2.19"
libobs-source-macro = { path = "../libobs-source-macro", version = "0.1.1" }
anyhow = "1.0.86"
paste = "1.0.15"

[features]
default = ["window-list"]
window-list = ["dep:libobs-window-helper"]
debug-tracing = ["libobs/debug-tracing", "libobs-wrapper/debug-tracing"]

[target.'cfg(target_family = "windows")'.dependencies]
display-info = "0.5.1"
libobs-window-helper = { version = "0.1.0", optional = true }

[dev-dependencies]
env_logger = "0.11.5"
essi-ffmpeg = "0.2.0"
lazy_static = "1.5.0"
tokio = "1.39.2"

[package.metadata]
libobs-version="30.2.2"
libobs-cache-dir="../obs-build"
