[package]
name = "libobs-sources"
description = "A helper crate to create sources for OBS"
version = "2.0.0"
repository = "https://github.com/joshprk/libobs-rs"
readme = "README.md"
authors = ["sshcrack"]
categories = [
    "multimedia::video",
    "multimedia::audio",
    "multimedia",
    "multimedia::encoding",
]
keywords = ["obs", "libobs", "video", "recording", "screen-recording"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
libobs = { package = "libobs", version = "2.0.3", path = "../libobs" }
libobs-wrapper = { path = "../libobs-wrapper", version = "3.0.0" }
num-derive = "0.4.2"
num-traits = "0.2.19"
libobs-source-macro = { path = "../libobs-source-macro", version = "2.0.0" }
anyhow = "1.0.97"
paste = "1.0.15"
duplicate = "2.0.0"
async-trait = "0.1.88"
log = "0.4.27"
remove-async-await = { version = "1.0.1", optional = true }

[features]
default = ["window-list"]
window-list = ["dep:libobs-window-helper"]
blocking = ["libobs-wrapper/blocking", "dep:remove-async-await"]

[target.'cfg(target_family = "windows")'.dependencies]
display-info = "0.5.4"
libobs-window-helper = { path = "../libobs-window-helper", version = "0.1.3", optional = true }

[dev-dependencies]
env_logger = "0.11.8"
essi-ffmpeg = "0.2.0"
lazy_static = "1.5.0"
tokio = "1.44.1"
