[package]
name = "libobs-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
libobs = { version = "0.1.3", path = "../libobs" }
display-info = "0.5.1"
num-derive = "0.4.2"
num-traits = "0.2.19"
