[package]
name = "libobs-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
libobs = { version = "0.1.3", path = "../libobs" }
display-info = "0.5.1"
num-derive = "0.4.2"
num-traits = "0.2.19"
lazy_static = "1.5.0"
crossbeam-channel = "0.5.13"
log = "0.4.22"
vsprintf = "2.0.0"
chrono = "0.4.38"


[package.metadata]
libobs-version="30.2.2"
libobs-cache-dir="../obs-build"
