[package]
name = "libobs-wrapper"
description = "A safe wrapper around libobs"
version = "2.0.3"
repository = "https://github.com/joshprk/libobs-rs"
readme = "README.md"
authors = ["sshcrack"]
categories = [
    "multimedia::video",
    "multimedia::audio",
    "multimedia",
    "multimedia::encoding",
]
keywords = ["obs", "libobs", "video", "recording", "screen-recording"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
libobs = { package = "libobs", version = "2.0.3", path = "../libobs" }
display-info = "0.5.4"
num-derive = "0.4.2"
num-traits = "0.2.19"
lazy_static = "1.5.0"
crossbeam-channel = "0.5.14"
log = "0.4.27"
vsprintf = "2.0.0"
chrono = "0.4.40"
getters0 = "0.1.1"
colored = { version = "3.0.0", optional = true }
parking_lot = "0.12.3"
oneshot = { version = "0.1.11", default-features = false, features = ["std"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.1", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_System_SystemInformation", "Win32_UI_WindowsAndMessaging"] }

[features]
default = ["color-logger"]
unsafe-send = []
color-logger = ["dep:colored"]
debug-tracing = ["libobs/debug-tracing"]
