name: Pull Request Validation

on:
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      # Run cargo check to ensure code will compile
      - name: Check code compilation
        run: cargo check --all
        shell: pwsh
      - name: Check code compilation for libobs-wrapper blocking
        run: cargo check --package libobs-wrapper --all-features
        shell: pwsh
      - name: Check code compilation for libobs-sources blocking
        run: cargo check --package libobs-sources --all-features
        shell: pwsh